name: Jira comment

on:
  push:
    branches:
      - junit-mockito

jobs:
  unit-teting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run unit tests with Maven
        id: maven-test
        run: mvn test

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        id: jacoco
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          fail-if-coverage-less-than: 50
          fail-if-branches-less-than: 50

      - name: Send notification
        if: success() || failure()
        id: get_comment
        run: |
          if [ ${{ steps.maven-test.conclusion}} == failure ]; then
            echo "comment=Test unitarios fallaron \n \
            Resumen: \n \
            Algunas de las pruebas unitarias no pasaron la ejecución">> "$GITHUB_OUTPUT"
          elif [ ${{ steps.jacoco.conclusion }} == failure ]; then
             echo "comment=Cobertura de código no ha sido aprobada \n \
              Resumen cobertura de código: \n \
                Cobertura de código: ${{ steps.jacoco.outputs.coverage }} \n \
                Cobertura de ramificaciones: ${{ steps.jacoco.outputs.branches }} \n
              Asegurese que la cobertura de código y ramificaciones cumpla con los requisitos establecidos">> "$GITHUB_OUTPUT"
          else
             echo "comment=Pruebas unitarias exitosas, cumplen con los criterios de aceptación. \
             Resumen cobertura de código: \n \
             Cobertura de código: ${{ steps.jacoco.outputs.coverage }} \n \
             Cobertura de ramificaciones: ${{ steps.jacoco.outputs.branches }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Curl
        if: success() || failure()
        run: |
          curl --request POST \
            --url 'https://nuamexchange.atlassian.net/rest/api/3/issue/ARQPD-41/comment' \
            --user 'alexander.rodriguez@nuamx.com:${{secrets.JIRA_TOKEN}}' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{
              "body": {
                "content": [
                  {
                    "content": [
                    {
                      "text": "${{steps.get_comment.outputs.comment}}",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                  }
                ],
                "type": "doc",
                "version": 1
              }
            }'
