name: Jira comment - Regex

on:
  push:
    branches:
      - release/ARQPD-41

jobs:
  unit-teting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get issue
        id: get_issue
        run: |
          var=${{github.ref_name}}
          echo "issue=$(echo $var | sed -E 's#.*/##')">> "$GITHUB_OUTPUT"

      - name: Run unit tests with Maven
        id: maven-test
        run: mvn test

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        id: jacoco
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          fail-if-coverage-less-than: 90
          fail-if-branches-less-than: 90

      - name: Send notification
        if: success() || failure()
        id: get_comment
        run: |
          if [ ${{ steps.maven-test.conclusion}} == failure ]; then
            echo "comment=Test unitarios fallaron \n \
            Resumen: \n \
            Algunas de las pruebas unitarias no pasaron la ejecución">> "$GITHUB_OUTPUT"
          elif [ ${{ steps.jacoco.conclusion }} == failure ]; then
             echo "comment=Cobertura de código no ha sido aprobada \n \
              Asegurese que la cobertura de código y ramificaciones cumpla con los requisitos establecidos \n \
              Cobertura requerida: \n \
                Cobertura de código: 50%  \n \
                Cobertura de ramificaciones: 50% ">> "$GITHUB_OUTPUT"
          else
            cobertura=$(printf "%.1f" $(echo '${{ steps.jacoco.outputs.coverage }}*100' | bc))
             branches=$(printf "%.1f" $(echo '${{ steps.jacoco.outputs.branches }}*100' | bc))
             echo "comment=Pruebas unitarias exitosas, cumplen con los criterios de aceptación \n \
             Resumen cobertura de código: \n \
             Cobertura de código: $cobertura  % \n \
             Cobertura de ramificaciones: $branches % " >> "$GITHUB_OUTPUT"
          fi


      - name: Curl
        if: success() || failure()
        run: |
          curl --request POST \
            --url 'https://nuamexchange.atlassian.net/rest/api/3/issue/${{steps.get_issue.outputs.issue}}/comment' \
            --user 'alexander.rodriguez@nuamx.com:${{secrets.JIRA_TOKEN}}' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{
              "body": {
                "content": [
                  {
                    "content": [
                    {
                      "text": "${{steps.get_comment.outputs.comment}}",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                  }
                ],
                "type": "doc",
                "version": 1
              }
            }'
