name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ] # development, release, production
  pull_request:
    branches: [ "main" ] # development, release, production

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3 # more documentation
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Generate a config.json
      run: |
        DOCKER_USERNAME=${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD=${{ secrets.DOCKER_TOKEN }}
        AUTH=$(echo -n "${DOCKER_USERNAME}:${DOCKER_PASSWORD}" | base64)
        cat <<EOF > config.json
        {
          "auths": {
            "https://index.docker.io/v1/": {
              "auth": "${AUTH}"
            }
          }
        }
        EOF

    - name: Cat
      run: |
        cat config.json

    - name: Build and push an image
      run: |
        docker run \
          -v `pwd`/config.json:/kaniko/.docker/config.json:ro \
          -v `pwd`:/workspace \
          gcr.io/kaniko-project/executor:debug \
          --dockerfile=Dockerfile \
          --destination $DOCKER_USERNAME/unit-testing:1.0

