name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ] # development, release, production
  pull_request:
    branches: [ "main" ] # development, release, production

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3 # more documentation
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: docker/login-action@v1
      with:
        registry: registry.nuamexchange.com
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Generate a config.json
      run: |
        cat <<JSON > config.json
        {
          "auths": {
            "registry.nuamexchange.com": {
              "username": "$(echo -n :${{ secrets.HARBOR_USERNAME }} | base64)"
              "password": "$(echo -n :${{ secrets.HARBOR_PASSWORD }} | base64)"
            }
          }
        }
        JSON

    - name: Cat
      run: |
        cat config.json
