name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ] # development, release, production
  pull_request:
    branches: [ "main" ] # development, release, production

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3 # more documentation
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: docker/login-action@v1
      with:
        registry: registry.nuamexchange.com
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Build and push an image
      run: |
        docker run \
          -v $(pwd):/workspace \
          -v $(pwd)/config.json:/kaniko/.docker/config.json:ro \
          gcr.io/kaniko-project/executor:latest \
            --context . \
            --dockerfile Dockerfile \
            --destination registry.nuamexchange.com/test-devops/jar-artifact:${{ github.run_number }} \
            --cache=true \
            --cache-repo registry.nuamexchange.com/test-devops/jar-artifact -cache


