name: Ref pull request

on:
  workflow_call:

jobs:
  pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Get issue Jira
        id: get_issue
        run: |
          var=${{github.base_ref}}
          echo "$var"
          echo "issue=$(echo $var | sed -E 's#.*/##')">> "$GITHUB_OUTPUT"
          echo "${{ github.event.pull_request.head.ref }}
